/**
 * Design-system constants shared by components — the Brutalist Editorial
 * system generated by ui-ux-pro-max (see `design-system/taptim/MASTER.md`).
 *
 * Colour values live in `index.css` under `@theme`, and the type scale is
 * expressed there as the `.type-*` utilities so the clamp() sizing lives in
 * one place. This file names the *decisions* that are otherwise just repeated
 * class strings, so spacing, surfaces, and muted-text pairings stay consistent.
 */

export const SPACING = {
  sectionY: 'py-20 sm:py-24',
  containerX: 'px-4 sm:px-6 lg:px-8',
  maxWidth: 'max-w-7xl',
} as const;

/**
 * The poster scale. `hero`/`display`/`section` are CSS utilities rather than
 * Tailwind chains because they carry clamp() sizing plus the negative tracking
 * and sub-1 line-height that make the type read as a poster instead of a
 * heading. `label` is the mono overline used for every small caps run.
 */
export const TYPE_SCALE = {
  hero: 'type-hero',
  display: 'type-display',
  section: 'type-section',
  h3: 'text-lg font-bold uppercase tracking-tight',
  body: 'text-base leading-relaxed',
  lead: 'text-lg leading-relaxed',
  small: 'text-sm',
  label: 'type-label',
  quote: 'type-quote',
} as const;

/**
 * Surfaces are hard 2px frames with a zero-blur offset shadow. `inverted` is
 * dark in both themes, so it must also carry `surface-dark` for the accent
 * token to resolve to its dark-side value.
 */
export const SURFACE = {
  card: 'brut-box brut-shadow',
  flat: 'brut-box',
  inverted: 'surface-dark border-2 border-ink-950 bg-ink-950 dark:border-ink-100',
  inset: 'bg-ink-50 dark:bg-ink-900/40',
} as const;

/**
 * Muted text is ink-600 rather than ink-500: on the newsprint background
 * ink-500 only reaches 4.0:1, under the 4.5:1 floor for body copy.
 */
export const TEXT = {
  muted: 'text-ink-600 dark:text-ink-400',
  strong: 'text-ink-950 dark:text-white',
  /** Accent as text; flips flame-700/flame-500 by theme for contrast. */
  accent: 'text-accent-text',
} as const;

/** Brutalism uses short, flat transitions — no long eased fades. */
export const TRANSITION = 'transition-colors duration-150';
